.script_template: &script_definition
    script:
        - ./script/setup.sh
        - ./script/buildonly.sh all
        - ./script/buildonly.sh package
        - ./build/Release/app/Sourcetrail --licenseFile ./setup/license.txt
        - cd ./bin/test
        - ../../build/Release/test/Sourcetrail_test

Linux64:
    image: st4ll1/coati_linux_64
    stage: deploy
    only:
        - master
        - triggers
    <<: *script_definition
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - Sourcetrail*.tar.gz
        expire_in: 3 days

Linux64_tag:
    image: st4ll1/coati_linux_64
    stage: deploy
    only:
        - tags
    <<: *script_definition
    artifacts:
        name: "$CI_JOB_NAME$CI_COMMIT_TAG"
        paths:
            - Sourcetrail*.tar.gz

Linux64_manual:
    image: st4ll1/coati_linux_64
    stage: deploy
    except:
        - master
    when: manual
    <<: *script_definition
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - Sourcetrail*.tar.gz

Linux64_licenseGenerator:
    image: st4ll1/coati_linux_64
    stage: deploy
    when: manual
    script:
        - ./script/setup.sh
        - ./script/buildonly.sh r keygen
        - mv build/Release/license_generator/Sourcetrail_license_generator .
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - Sourcetrail_license_generator
        expire_in: 3 days

Linux32:
    image: st4ll1/coati_linux_32
    stage: deploy
    only:
        - master
        - triggers
    <<: *script_definition
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - Sourcetrail*.tar.gz
        expire_in: 3 days

Linux32_tag:
    image: st4ll1/coati_linux_32
    stage: deploy
    only:
        - tags
    <<: *script_definition
    artifacts:
        name: "$CI_JOB_NAME$CI_COMMIT_TAG"
        paths:
            - Sourcetrail*.tar.gz

Linux32_manual:
    image: st4ll1/coati_linux_32
    stage: deploy
    except:
        - master
    when: manual
    <<: *script_definition
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - Sourcetrail*.tar.gz
