Linux64:
    image: st4ll1/coati_linux_64
    stage: deploy
    only:
        - master
        - triggers
    script:
        - ./script/setup.sh
        - ./script/buildonly.sh all
        - ./script/buildonly.sh package
        - ./build/Release/app/Coati --licenseFile ./setup/license.txt
        - cd ./bin/test
        - ../../build/Release/test/Coati_test
    artifacts:
        paths:
            - distr/Coati*.tar.gz
        expire_in: 3 days

Linux64_tagged:
    image: st4ll1/coati_linux_64
    stage: deploy
    only:
        - tags
    script:
        - ./script/setup.sh
        - ./script/buildonly.sh all
        - ./script/buildonly.sh package
        - ./build/Release/app/Coati --licenseFile ./setup/license.txt
        - cd ./bin/test
        - ../../build/Release/test/Coati_test
    artifacts:
        paths:
            - distr/Coati*.tar.gz

Linux32:
    image: st4ll1/coati_linux_32
    stage: deploy
    only:
        - master
        - triggers
    script:
        - ./script/setup.sh
        - ./script/buildonly.sh all
        - ./script/buildonly.sh package
        - ./build/Release/app/Coati --licenseFile ./setup/license.txt
        - cd ./bin/test
        - ../../build/Release/test/Coati_test
    artifacts:
        paths:
            - distr/Coati*.tar.gz
        expire_in: 3 days

Linux32_tag:
    image: st4ll1/coati_linux_32
    stage: deploy
    only:
        - tags
    script:
        - ./script/setup.sh
        - ./script/buildonly.sh all
        - ./script/buildonly.sh package
        - ./build/Release/app/Coati --licenseFile ./setup/license.txt
        - cd ./bin/test
        - ../../build/Release/test/Coati_test
    artifacts:
        paths:
            - distr/Coati*.tar.gz
