version: 0.0.0.{build}
image: Visual Studio 2017

install:
  - docker build -t coatisoftware/local deployment/dockerfiles/windows/travis_ci


build_script:
  - docker run --name builder coatisoftware/local 
 